Fixed np.concatenate related crash when fitting with sparse arrays
As mentioned in #71 feeding sparse arrays to .fit caused
```
ValueError: zero-dimensional arrays cannot be concatenated
```
to be raised. This fixes the issue.